name: 🐞 Bug
description: File a bug/issue
title: "[BUG] <title>"
labels: ["Bug", "Needs Triage"]
body:
- type: checkboxes
  attributes:
    label: ¿Duplicado?
    description: Por favor, busca si ya existe una incidencia para el fallo que has encontrado.
    options:
    - label: He revisado los bugs ya reportados.
      required: true
- type: textarea
  attributes:
    label: Descripción
    description: ""
  validations:
    required: true
- type: textarea
  attributes:
    label: Precondiciones
    description: ""
  validations:
    required: false
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. 
      2. 
      3. 
      4.
      5.
  validations:
    required: false
- type: textarea
  attributes:
    label: Resultado esperado
    description: ""
  validations:
    required: true
- type: textarea
  attributes:
    label: Resultado obtenido
    description: ""
  validations:
    required: true
- type: textarea
  attributes:
    label: Environment
    description: ""
    value: |
         - OS:
         - Version:
         - Browsers:
    render: markdown
  validations:
    required: false

