name: 🐞 Bug
description: File a bug/issue
title: "[AREA] title"
labels: ["Bug", "Needs Triage"]
body:
- type: checkboxes
  attributes:
    label: ¿Duplicado?
    description: Por favor, busca si ya existe una incidencia para el fallo que has encontrado.
    options:
    - label: El bug no ha sido reportado previamente.
      required: true
- type: textarea
  attributes:
    label: Descripción
    description: Breve descripción del bug encontrado.
  validations:
    required: true
- type: textarea
  attributes:
    label: Precondiciones
    description: Condiciones necesarias para replicar el bug.
  validations:
    required: false
- type: textarea
  attributes:
    label: Pasos para reproducir
    value: |
      1. 
      2. 
      3. 
      4.
      5.
    render: markdown
  validations:
    required: false
- type: textarea
  attributes:
    label: Resultado esperado
  validations:
    required: true
- type: textarea
  attributes:
    label: Resultado obtenido
  validations:
    required: true
- type: textarea
  attributes:
    label: Ambiente
    value: |
         - OS:
         - Version:
         - Browsers:
    render: markdown
  validations:
    required: false
- type: dropdown
  id: Severidad
  attributes:
    label: Severidad
    options: 
      - Critical
      - High
      - Medium
      - Low
  validations:
    required: true
- type: textarea
  attributes:
    label: Notas adicionales
  validations:
    required: false

