name: Bug
description: File a bug/issue
title: "[BUG] <title>"
labels: [Bug, Needs Triage]
body:
  - type: checkboxes
    attributes:
      label: Is it already reported?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: There is no existing report for this issue.
          required: true
  - type: textarea
    attributes:
      label: Description
      description: Write a brief description of what is happening
      validations:
        required: true
  - type: textarea
    attributes:
      label: Workaround
      description: ""
      validations:
        required: false
  - type: textarea
    attributes:
      label: Preconditions
      description: ""
      validations:
        required: false
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: ""
      validations:
        required: true
  - type: textarea
    attributes:
      label: Expected behavior
      description: ""
      validations:
        required: true
  - type: textarea
    attributes:
      label: Actual behavior
      description: ""
      validations:
        required: true
  - type: textarea
    attributes:
      label: Severity
      description: Low / Medium / High
      validations:
        required: true
  - type: textarea
    attributes:
      description: OS / Version
      validations:
        required: false
  - type: textarea
    attributes:
      description: In which browser the issue is reproduced?
      validations:
        required: false
      
      
