name: Bug
description: File a bug/issue 
title: "[BUG] <title>"
labels: [Bug, Needs Triage]
body: 
- type: checkboxes
  atributes:
    label: Is it already reported?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: The is no existing report for this issue.
      required: true
- type: textarea
  atributes:
      label: Description
      description: Write a brief description of what is happening
      validations:
        required: true
- type: textarea
  atributes:
      label: Workaround
      description: 
      validations:
        required: false
- type: textarea
  atributes:
      label: Preconditions
      description: 
      validations:
        required: false
- type: textarea
  atributes:
      label: Steps to reproduce
      description: 
      validations:
        required: true
- type: textarea
  atributes:
      label: Expected behavior
      description: 
      validations:
        required: true
- type: textarea
  atributes:
      label: Actual behavior
      description: 
      validations:
        required: true
- type: textarea
  atributes:
      label: Severity
      description: Low / Medium / High
      validations:
        required: true
- type: textarea
  atributes:
      label: Environment
        values: |
          OS:
          Version
        render: markdown
      validations:
        required: true
- type: dropdown
    id: browsers
    atributes:
      label:
      multiple: true
      options: 
      - Firefox
      - Google chrome
      - Microsoft Edge
      - Brave
      - Safari
      - Opera GX
      
      
