name: Test Case
description: Test Case template
title: "<title>"
labels: ["Test Case"]
body:
- type: textarea
  attributes:
    label: Descripción
    description: Breve descripción del caso de prueba.
  validations:
    required: true
- type: textarea
  attributes:
    label: Pasos para reproducir
    value: |
      1. 
      2. 
      3. 
      4.
      5.
    render: markdown
  validations:
    required: false
- type: checkboxes
  attributes:
    label: Passed
    description: Por favor, busca si ya existe una incidencia para el fallo que has encontrado.
    options:
    - label: Passed
      required: false
  attributes:
    label: Failed
    description: Por favor, busca si ya existe una incidencia para el fallo que has encontrado.
    options:
    - label: Failed
      required: false
    
