name: Test Case
description: Test Case template
title: "<title>"
labels: ["Test Case"]
body:
- type: checkboxes
  attributes:
    label: ¿Duplicado?
    description: Por favor, busca si ya existe una incidencia para el fallo que has encontrado.
    options:
    - label: He revisado los bugs ya reportados.
      required: true
